ARG version
FROM --platform=linux/arm64/v8 ghcr.io/gimlet-io/jammy-build:${version}

RUN mkdir platform && mkdir buildpacks

COPY buildpacks/paketo-buildpacks_node-engine buildpacks/paketo-buildpacks_node-engine
COPY buildpacks/paketo-buildpacks_npm-start buildpacks/paketo-buildpacks_npm-start
COPY buildpacks/paketo-buildpacks_npm-install buildpacks/paketo-buildpacks_npm-install

COPY lifecycle lifecycle

# COPY --chown=image-builder:image-builder bin/image-builder-linux-arm64-v8 /bin/image-builder

ENV CNB_PLATFORM_API=0.7

EXPOSE 5000
CMD ["/bin/image-builder"]
