tasks:
  - init: |
      cat << EOF > $PWD/.env
      GIMLET_SERVER=$GIMLET_SERVER
      GIMLET_TOKEN=$GIMLET_TOKEN
      EOF

      sudo cp docker/known_hosts /etc/ssh/ssh_known_hosts

      curl -L https://github.com/gimlet-io/gimlet-cli/releases/download/v0.12.2/gimlet-$(uname)-$(uname -m) -o gimlet
      chmod +x gimlet
      sudo mv ./gimlet /usr/local/bin/gimlet
      gimlet --version

      cat << EOF > ~/.gimlet/config
      export GIMLET_SERVER=http://127.0.0.1:8888
      EOF

      cat << EOF > $PWD/.env
      GITOPS_REPO=$GITOPS_REPO
      GITOPS_REPO_DEPLOY_KEY_PATH=/workspace/gimletd/deploykey
      PRINT_ADMIN_TOKEN=true

      NOTIFICATIONS_PROVIDER=slack
      NOTIFICATIONS_TOKEN=$SLACK_TOKEN
      NOTIFICATIONS_DEFAULT_CHANNEL=gimletd
      EOF

      echo $DEPLOY_KEY | base64 -d > deploykey
      echo $DEPLOY_KEY_PUB | base64 -d > deploykey.pub
      chmod 500 deploykey
      chmod 500 deploykey.pub
  - name: vscode settings
    init: |
      mkdir -p "$PWD/.vscode";
      cat << 'EOF' > "$PWD/.vscode/settings.json"
        {
          "terminal.integrated.fontFamily": "Monospace",
          "terminal.integrated.fontSize": 14,
          "window.zoomLevel": 1
        }
      EOF
      exit

ports:
  - port: 8889
    onOpen: ignore
  - port: 8888
    onOpen: ignore
    visibility: public
  - port: 6060
    onOpen: ignore

vscode:
  extensions:
    - golang.go

gitConfig:
  alias.st: status
  alias.l: log --graph --pretty=default
  alias.lola: log --graph --oneline --all
  alias.fp: fetch --prune
