tasks:
  - init: |
      cat << EOF > $PWD/.env
      GIMLET_SERVER=$GIMLET_SERVER
      GIMLET_TOKEN=$GIMLET_TOKEN
      EOF

      make all

vscode:
  extensions:
    - golang.go

gitConfig:
  alias.st: status
  alias.l: log --graph --pretty=default
  alias.lola: log --graph --oneline --all
  alias.fp: fetch --prune
