tasks:
  - init: |
      bash fixtures/gitpod/setupEnvForCLI.sh
      bash fixtures/gitpod/setupEnvForGimletD.sh
      bash fixtures/gitpod/setupEnvForGimletDashboard.sh
  - name: vscode settings
    init: |
      mkdir -p "$PWD/.vscode";
      cat << 'EOF' > "$PWD/.vscode/settings.json"
        {
          "terminal.integrated.fontFamily": "Monospace",
          "terminal.integrated.fontSize": 14,
          "window.zoomLevel": 1
        }
      EOF
      exit

ports:
  - port: 8889
    onOpen: ignore
  - port: 8888
    onOpen: ignore
    visibility: public
  - port: 6060
    onOpen: ignore
  - port: 9000
    onOpen: ignore
    visibility: public
  - port: 9001
    onOpen: ignore
  - port: 3000
    onOpen: open-browser
    visibility: public

vscode:
  extensions:
    - golang.go

gitConfig:
  alias.st: status
  alias.l: log --graph --pretty=default
  alias.lola: log --graph --oneline --all
  alias.fp: fetch --prune
